name: AWS example workflow
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: "foodimagekarl"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Show AWS CLI version
        run: aws --version

      - name: List files in the current directory
        run: ls -la

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::821238824534:role/github
          aws-region: ${{ env.AWS_REGION }}

      - name: Copy index.html to S3
        run: |
          aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}
